In [1]:
from pathlib import Path
import sys

print("Current working directory:")
print(Path.cwd())

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
SRC_PATH = PROJECT_ROOT / "src"

print("\nProject root:")
print(PROJECT_ROOT)

print("\nSRC path:")
print(SRC_PATH)

print("\nDoes SRC path exist?")
print(SRC_PATH.exists())

print("\nWhat is inside SRC?")
if SRC_PATH.exists():
    print(list(SRC_PATH.iterdir()))

Current working directory:
c:\Users\htaus\Desktop\Ultimate Frisbee Analytics\notebooks

Project root:
c:\Users\htaus\Desktop\Ultimate Frisbee Analytics

SRC path:
c:\Users\htaus\Desktop\Ultimate Frisbee Analytics\src

Does SRC path exist?
True

What is inside SRC?
[WindowsPath('c:/Users/htaus/Desktop/Ultimate Frisbee Analytics/src/ufa')]

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path(r"C:\Users\htaus\Desktop\Ultimate Frisbee Analytics")
SRC_PATH = PROJECT_ROOT / "src"

sys.path.insert(0, str(SRC_PATH))

print(SRC_PATH)
print(SRC_PATH.exists())

C:\Users\htaus\Desktop\Ultimate Frisbee Analytics\src
True

In [3]:
from ufa.client import get_games, get_game_events
from ufa.clean import clean_game_events 
from ufa.metrics import calculate_thrower_stats

In [4]:
import requests

BASE_URL = "https://www.backend.ufastats.com/api/v1"

response = requests.get(
    f"{BASE_URL}/games",
    params={"date": "2024-06-08"}
)

print(response.url)
print(response.status_code)
print(response.text[:1000])

https://www.backend.ufastats.com/api/v1/games?date=2024-06-08
200
{"object":"list","data":[{"gameID":"2024-06-08-LA-POR","awayTeamID":"aviators","homeTeamID":"steel","awayScore":21,"homeScore":22,"status":"Final","startTimestamp":"2024-06-08T16:00:00-07:00","startTimezone":"PDT","streamingURL":"https://watchufa.tv/videos/los-angeles-at-portland-6-8-2024","updateTimestamp":"2024-06-10T05:04:32.918Z","week":"week-7","location":"Kiggins Bowl"},{"gameID":"2024-06-08-NY-DC","awayTeamID":"empire","homeTeamID":"breeze","awayScore":14,"homeScore":16,"status":"Final","startTimestamp":"2024-06-08T19:00:00-04:00","startTimezone":"EDT","streamingURL":"https://watchufa.tv/videos/new-york-at-dc-6-8-2024","updateTimestamp":"2024-06-09T00:56:11.144Z","week":"week-7","location":"Carlini Field, Catholic U"},{"gameID":"2024-06-08-MIN-IND","awayTeamID":"windchill","homeTeamID":"alleycats","awayScore":24,"homeScore":21,"status":"Final","startTimestamp":"2024-06-08T18:30:00-04:00","startTimezone":"EDT","streamingURL":"https://watchufa.tv/videos/minnesota-at-indianapolis-6

In [5]:
games = get_games("2024-06-08")
games.head()

,gameID,awayTeamID,homeTeamID,awayScore,homeScore,status,startTimestamp,startTimezone,streamingURL,updateTimestamp,week,location
0,2024-06-08-LA-POR,aviators,steel,21,22,Final,2024-06-08T16:00:00-07:00,PDT,https://watchufa.tv/videos/los-angeles-at-port...,2024-06-10T05:04:32.918Z,week-7,Kiggins Bowl
1,2024-06-08-NY-DC,empire,breeze,14,16,Final,2024-06-08T19:00:00-04:00,EDT,https://watchufa.tv/videos/new-york-at-dc-6-8-...,2024-06-09T00:56:11.144Z,week-7,"Carlini Field, Catholic U"
2,2024-06-08-MIN-IND,windchill,alleycats,24,21,Final,2024-06-08T18:30:00-04:00,EDT,https://watchufa.tv/videos/minnesota-at-indian...,2024-06-09T00:39:17.021Z,week-7,Grand Park Events Center
3,2024-06-08-COL-SLC,apex,shred,20,19,Final,2024-06-08T19:00:00-06:00,MDT,https://www.watchufa.tv/week-7/videos/colorado...,2024-06-09T21:53:10.966Z,week-7,Zion Bank Stadium
4,2024-06-08-PHI-BOS,phoenix,glory,12,22,Final,2024-06-08T19:00:00-04:00,EDT,https://watchufa.tv/videos/philadelphia-at-bos...,2024-06-22T22:36:41.012Z,week-7,Hormel Stadium

In [6]:
game_id = games.loc[0, "gameID"]

events = get_game_events(game_id)
throws = clean_game_events(events)
player_stats = calculate_thrower_stats(throws)

player_stats.sort_values("attempts", ascending=False).head(20)

,thrower,attempts,completions,turnovers,avg_throw_distance,completion_pct
26,pjanas,71,70,1,19.687419,0.985915
7,dbarram,54,52,2,22.735711,0.962963
1,arueda,37,36,1,15.567189,0.972973
20,kmccracke,37,36,1,16.128171,0.972973
17,jsnyder,31,30,1,17.445535,0.967742
28,rgretsch,29,27,2,17.440300,0.931034
23,msteiner,26,24,2,18.536434,0.923077
31,sradlauer,24,23,1,21.723169,0.958333
12,hwayte,23,22,1,13.650033,0.956522
27,qbuermeye,22,21,1,13.899699,0.954545
10,eshapiro,22,20,2,19.790317,0.909091
29,smcdougal,20,19,1,16.696619,0.950000
22,mkiyoi,13,11,2,15.256080,0.846154
8,dmcnally,12,12,0,18.700435,1.000000
21,mdomingue,12,12,0,11.287110,1.000000
4,bgeorge,11,11,0,17.857416,1.000000
6,cstillwel,10,9,1,20.233657,0.900000
5,ceustis,9,9,0,16.918489,1.000000
19,kgoldberg,8,8,0,24.366007,1.000000
33,tschaidhe,8,8,0,13.162952,1.000000

In [ ]:
throws.head().T

    type    thrower   receiver defender  completion  turnover  throw_distance
1     18     arueda    dbarram      NaN           1         0       10.513468
2     18    dbarram     arueda      NaN           1         0        8.146195
3     18     arueda    jsnyder      NaN           1         0       18.373331
4     18    jsnyder     hwayte      NaN           1         0       11.410986
5     18     hwayte  qbuermeye      NaN           1         0       15.382292
6     18  qbuermeye    jsnyder      NaN           1         0       11.063187
7     18    jsnyder  sradlauer      NaN           1         0       21.496421
8     18  sradlauer     arueda      NaN           1         0       20.748381
9     18     arueda  qbuermeye      NaN           1         0        7.763092
10    18  qbuermeye  cstillwel      NaN           1         0       16.213257
11    18  cstillwel  qbuermeye      NaN           1         0        9.635372
12    18  qbuermeye    dbarram      NaN           1         0       18.904021
13    18    dbarram  cstillwel      NaN           1         0       25.061798
14    18  cstillwel     arueda      NaN           1         0       16.644212
15    19     arueda  sradlauer      NaN           1         0       14.879550
21    18    jsnyder    dbarram      NaN           1         0        8.619849
22    18    dbarram  tschaidhe      NaN           1         0        9.890222
23    18  tschaidhe  sradlauer      NaN           1         0       18.950517
24    18  sradlauer  cstillwel      NaN           1         0       59.948529
25    18  cstillwel    dbarram      NaN           1         0       19.844468
26    19    dbarram     hwayte      NaN           1         0        7.717493
31    18     arueda    dbarram      NaN           1         0       12.053390
32    18    dbarram  sradlauer      NaN           1         0       19.915916
33    18  sradlauer    dbarram      NaN           1         0       17.148006
34    18    dbarram     hwayte      NaN           1         0       24.470660
35    18     hwayte     arueda      NaN           1         0       12.608874
36    18     arueda    dbarram      NaN           1         0       11.898290
37    18    dbarram    jsnyder      NaN           1         0       18.646890
38    19    jsnyder  cstillwel      NaN           1         0       59.700595
42    19     arueda    zheiden      NaN           1         0       14.056248

In [9]:
throws[["type", "thrower", "receiver", "defender", "completion", "turnover", "throw_distance"]].head(30)

    type    thrower   receiver defender  completion  turnover  throw_distance
1     18     arueda    dbarram      NaN           1         0       10.513468
2     18    dbarram     arueda      NaN           1         0        8.146195
3     18     arueda    jsnyder      NaN           1         0       18.373331
4     18    jsnyder     hwayte      NaN           1         0       11.410986
5     18     hwayte  qbuermeye      NaN           1         0       15.382292
6     18  qbuermeye    jsnyder      NaN           1         0       11.063187
7     18    jsnyder  sradlauer      NaN           1         0       21.496421
8     18  sradlauer     arueda      NaN           1         0       20.748381
9     18     arueda  qbuermeye      NaN           1         0        7.763092
10    18  qbuermeye  cstillwel      NaN           1         0       16.213257
11    18  cstillwel  qbuermeye      NaN           1         0        9.635372
12    18  qbuermeye    dbarram      NaN           1         0       18.904021
13    18    dbarram  cstillwel      NaN           1         0       25.061798
14    18  cstillwel     arueda      NaN           1         0       16.644212
15    19     arueda  sradlauer      NaN           1         0       14.879550
21    18    jsnyder    dbarram      NaN           1         0        8.619849
22    18    dbarram  tschaidhe      NaN           1         0        9.890222
23    18  tschaidhe  sradlauer      NaN           1         0       18.950517
24    18  sradlauer  cstillwel      NaN           1         0       59.948529
25    18  cstillwel    dbarram      NaN           1         0       19.844468
26    19    dbarram     hwayte      NaN           1         0        7.717493
31    18     arueda    dbarram      NaN           1         0       12.053390
32    18    dbarram  sradlauer      NaN           1         0       19.915916
33    18  sradlauer    dbarram      NaN           1         0       17.148006
34    18    dbarram     hwayte      NaN           1         0       24.470660
35    18     hwayte     arueda      NaN           1         0       12.608874
36    18     arueda    dbarram      NaN           1         0       11.898290
37    18    dbarram    jsnyder      NaN           1         0       18.646890
38    19    jsnyder  cstillwel      NaN           1         0       59.700595
42    19     arueda    zheiden      NaN           1         0       14.056248

In [11]:
throws.to_csv(f"../data/processed/game_{game_id}_throws.csv", index=False)

In [14]:
events[["type", "thrower", "receiver", "puller", "defender", "turnoverX", "turnoverY"]].head(50)

    type    thrower   receiver     puller defender  turnoverX  turnoverY
0      2        NaN        NaN        NaN      NaN        NaN        NaN
1     18     arueda    dbarram        NaN      NaN        NaN        NaN
2     18    dbarram     arueda        NaN      NaN        NaN        NaN
3     18     arueda    jsnyder        NaN      NaN        NaN        NaN
4     18    jsnyder     hwayte        NaN      NaN        NaN        NaN
5     18     hwayte  qbuermeye        NaN      NaN        NaN        NaN
6     18  qbuermeye    jsnyder        NaN      NaN        NaN        NaN
7     18    jsnyder  sradlauer        NaN      NaN        NaN        NaN
8     18  sradlauer     arueda        NaN      NaN        NaN        NaN
9     18     arueda  qbuermeye        NaN      NaN        NaN        NaN
10    18  qbuermeye  cstillwel        NaN      NaN        NaN        NaN
11    18  cstillwel  qbuermeye        NaN      NaN        NaN        NaN
12    18  qbuermeye    dbarram        NaN      NaN        NaN        NaN
13    18    dbarram  cstillwel        NaN      NaN        NaN        NaN
14    18  cstillwel     arueda        NaN      NaN        NaN        NaN
15    19     arueda  sradlauer        NaN      NaN        NaN        NaN
16     1        NaN        NaN        NaN      NaN        NaN        NaN
17     7        NaN        NaN    unknown      NaN        NaN        NaN
18    16        NaN        NaN        NaN      NaN        NaN        NaN
19    15        NaN        NaN        NaN      NaN        NaN        NaN
20     2        NaN        NaN        NaN      NaN        NaN        NaN
21    18    jsnyder    dbarram        NaN      NaN        NaN        NaN
22    18    dbarram  tschaidhe        NaN      NaN        NaN        NaN
23    18  tschaidhe  sradlauer        NaN      NaN        NaN        NaN
24    18  sradlauer  cstillwel        NaN      NaN        NaN        NaN
25    18  cstillwel    dbarram        NaN      NaN        NaN        NaN
26    19    dbarram     hwayte        NaN      NaN        NaN        NaN
27     1        NaN        NaN        NaN      NaN        NaN        NaN
28     7        NaN        NaN  pbuermeye      NaN        NaN        NaN
29    15        NaN        NaN        NaN      NaN        NaN        NaN
30     2        NaN        NaN        NaN      NaN        NaN        NaN
31    18     arueda    dbarram        NaN      NaN        NaN        NaN
32    18    dbarram  sradlauer        NaN      NaN        NaN        NaN
33    18  sradlauer    dbarram        NaN      NaN        NaN        NaN
34    18    dbarram     hwayte        NaN      NaN        NaN        NaN
35    18     hwayte     arueda        NaN      NaN        NaN        NaN
36    18     arueda    dbarram        NaN      NaN        NaN        NaN
37    18    dbarram    jsnyder        NaN      NaN        NaN        NaN
38    19    jsnyder  cstillwel        NaN      NaN        NaN        NaN
39     1        NaN        NaN        NaN      NaN        NaN        NaN
40     7        NaN        NaN    zheiden      NaN        NaN        NaN
41    11        NaN        NaN        NaN   jsaunt        NaN        NaN
42    19     arueda    zheiden        NaN      NaN        NaN        NaN
43     1        NaN        NaN        NaN      NaN        NaN        NaN
44     7        NaN        NaN    zheiden      NaN        NaN        NaN
45    11        NaN        NaN        NaN  zheiden        NaN        NaN
46    18    zheiden    ceustis        NaN      NaN        NaN        NaN
47    18    ceustis    zheiden        NaN      NaN        NaN        NaN
48    18    zheiden     jsaunt        NaN      NaN        NaN        NaN
49    18     jsaunt  ballahdad        NaN      NaN        NaN        NaN