In [1]:
import sys
from pathlib import Path

sys.path.insert(0, "../src")

import pandas as pd

from ufa import (
    prepare_all_games_training_data,
    train_etv_models,
    build_etv_model,
    save_model_bundle,
    build_game_throws,
)

In [2]:
training_throws = prepare_all_games_training_data("../data/raw/all_games_1024.csv")

print("Training games:", training_throws["gameID"].nunique())
print("Training throws:", len(training_throws))
print("Completion rate:", training_throws["completion"].mean().round(3))
print("Point outcome rate:", training_throws["point_outcome"].mean().round(3))

training_throws[[
    "gameID",
    "thrower",
    "receiver",
    "completion",
    "point_outcome",
    "throw_distance",
    "times",
]].head(20)

Training games: 574
Training throws: 290826
Completion rate: 0.932
Point outcome rate: 0.71

,gameID,thrower,receiver,completion,point_outcome,throw_distance,times
0,2023-06-24-DC-BOS,jnissen,jmalks,1,1,12.430326,2880.000000
1,2023-06-24-DC-BOS,jmalks,jnissen,1,1,10.948397,2876.578947
2,2023-06-24-DC-BOS,jnissen,jmalks,1,1,13.982221,2873.157895
3,2023-06-24-DC-BOS,jmalks,jnissen,1,1,9.227448,2869.736842
4,2023-06-24-DC-BOS,jnissen,boort,1,1,19.372426,2866.315789
5,2023-06-24-DC-BOS,boort,jmalks,1,1,11.366653,2862.894737
6,2023-06-24-DC-BOS,jmalks,jnissen,1,1,11.147242,2859.473684
7,2023-06-24-DC-BOS,jnissen,khealey,1,1,12.570143,2856.052632
8,2023-06-24-DC-BOS,khealey,jnissen,1,1,6.413774,2852.631579
9,2023-06-24-DC-BOS,jnissen,cboxley,1,1,11.741082,2849.210526
10,2023-06-24-DC-BOS,cboxley,mmcdonnel,1,1,8.807383,2845.789474
11,2023-06-24-DC-BOS,mmcdonnel,cboxley,1,1,9.183779,2842.368421
12,2023-06-24-DC-BOS,cboxley,jmalks,1,1,13.356893,2838.947368
13,2023-06-24-DC-BOS,jmalks,cboxley,1,1,9.446523,2835.526316
14,2023-06-24-DC-BOS,cboxley,jnissen,1,1,29.100421,2832.105263
15,2023-06-24-DC-BOS,jnissen,cboxley,1,1,6.976855,2828.684211
16,2023-06-24-DC-BOS,cboxley,jnissen,1,1,8.770433,2825.263158
17,2023-06-24-DC-BOS,jnissen,tmonroe,1,1,5.993038,2821.842105
18,2023-06-24-DC-BOS,tmonroe,mmcdonnel,1,1,5.470960,2818.421053
19,2023-06-24-DC-BOS,mmcdonnel,jmalks,1,1,16.573838,2815.000000

In [3]:
training_throws[[
    "thrower_x",
    "thrower_y",
    "receiver_x",
    "receiver_y",
    "throw_distance",
    "throw_angle",
    "y_diff",
    "x_diff",
    "times",
    "completion_target",
    "eventual_score_target",
]].describe()

,thrower_x,thrower_y,receiver_x,receiver_y,throw_distance,throw_angle,y_diff,x_diff,times,completion_target,eventual_score_target
count,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000
mean,0.395374,51.250743,0.458543,59.614521,16.602010,42.819928,8.363779,0.063169,1458.822921,0.931784,0.710284
std,13.015376,23.307959,13.099142,26.217124,11.496298,94.380627,14.080941,11.813662,837.180475,0.252117,0.453631
min,-26.670000,0.000000,-26.670000,0.000000,0.000000,-179.974524,-83.230000,-52.850000,-297.000000,0.000000,0.000000
25%,-9.830000,32.590000,-10.100000,38.450000,10.067765,-0.631030,-0.070000,-8.800000,738.142857,1.000000,0.000000
50%,0.220000,49.630000,0.430000,57.220000,13.792103,62.017843,6.480000,0.210000,1470.444444,1.000000,1.000000
75%,10.770000,70.090000,11.220000,79.220000,18.781129,110.783936,12.960000,8.730000,2187.666667,1.000000,1.000000
max,26.660000,100.000000,26.660000,120.000000,101.211757,180.000000,99.070000,53.330000,2880.000000,1.000000,1.000000

In [4]:
model_bundle = train_etv_models(training_throws)
etv_model = build_etv_model(model_bundle)

In [5]:
Path("../models").mkdir(exist_ok=True)

save_model_bundle(model_bundle, "../models/all_games_baseline_etv_model.joblib")

'../models/all_games_baseline_etv_model.joblib'

In [6]:
# Train on many games above, then inspect one held-out/display game here.
display_game_id = "2024-06-08-NY-DC"

result = build_game_throws(
    game_id=display_game_id,
    etv_model=etv_model,
)

result.throws[
    ["thrower", "receiver", "completion", "xcp", "etv", "cpoe", "t_ec", "r_ec", "total_ec"]
].head(20)

,thrower,receiver,completion,xcp,etv,cpoe,t_ec,r_ec,total_ec
5,tedmonds,jtom,1,0.975129,0.579782,0.024871,0.013005,0.035807,0.048812
6,jtom,dbloodgoo,1,0.969610,0.613335,0.030390,-0.002254,0.044181,0.041927
7,dbloodgoo,cmccutche,1,0.959331,0.661362,0.040669,0.003846,0.059572,0.063419
8,cmccutche,tedmonds,1,0.978755,0.690290,0.021245,-0.030644,0.031120,0.000476
9,tedmonds,dbloodgoo,1,0.974197,0.678207,0.025803,-0.043204,0.037789,-0.005415
10,dbloodgoo,cjurek,1,0.950876,0.688779,0.049124,-0.027216,0.071875,0.044659
11,cjurek,tedmonds,1,0.976928,0.725309,0.023072,-0.035346,0.033763,-0.001583
12,tedmonds,cjurek,1,0.972800,0.706313,0.027200,-0.052759,0.039839,-0.012920
13,cjurek,tedmonds,1,0.968168,0.716961,0.031832,-0.029191,0.046560,0.017369
14,tedmonds,cjurek,1,0.755617,0.620604,0.244383,-0.142917,0.379396,0.236479
22,cjurek,jmalks,1,0.990154,0.497502,0.009846,-0.013485,0.013485,0.000000
23,jmalks,aroy,1,0.969799,0.529884,0.030201,0.018897,0.042922,0.061819
24,aroy,ebonnet,1,0.965890,0.584506,0.034110,0.011699,0.049336,0.061036
25,ebonnet,cjurek,1,0.975773,0.612977,0.024227,-0.020865,0.035154,0.014288
26,cjurek,jmalks,1,0.963271,0.652555,0.036729,0.004424,0.053756,0.058181
27,jmalks,ebonnet,1,0.760958,0.511002,0.239042,-0.195309,0.339307,0.143998
28,ebonnet,jnissen,1,0.902587,0.848822,0.097413,-0.001487,0.151178,0.149690
33,gnorrbom,aroy,1,0.972676,0.543213,0.027324,0.031131,0.038952,0.070082
34,aroy,ebonnet,1,0.970860,0.597255,0.029140,0.015090,0.042203,0.057292
35,ebonnet,tmonroe,1,0.956907,0.648444,0.043093,0.008987,0.063093,0.072080

In [7]:
print("Display game:", result.game_id)
print("Throws with attached defender/block:", result.throws["defender"].notna().sum())
print("Box score total blocks:", result.box_score_stats["B"].sum())

result.box_score_stats.sort_values("B", ascending=False).head(40)

Display game: 2024-06-08-NY-DC
Throws with attached defender/block: 12
Box score total blocks: 12.0

,player,G,A,HA,T,B,C,CP%,HuR,HuCP%,...,total_t_aec,avg_t_aec,total_r_aec,avg_r_aec,total_total_aec,avg_total_aec,total_etv,avg_etv,expected_completions,completions_over_expected
17,adavis2,1.0,0,0.0,0,3.0,3,1.000000,0.000000,NaN,...,-0.141318,-0.047106,0.585888,0.195296,0.444570,0.148190,1.900071,0.633357,2.864090,0.135910
3,bjagt,2.0,2,0.0,0,2.0,19,1.000000,0.052632,1.000000,...,-2.951374,-0.155335,6.156002,0.324000,3.204629,0.168665,12.985366,0.683440,17.961387,1.038613
5,jmalks,1.0,4,1.0,2,1.0,27,0.931034,0.068966,1.000000,...,-2.226520,-0.076777,7.477736,0.257853,5.251217,0.181076,18.896001,0.651586,27.428805,-0.428805
1,cjurek,2.0,3,2.0,1,1.0,26,0.962963,0.037037,0.000000,...,-4.968628,-0.184023,8.258974,0.305888,3.290346,0.121865,19.096755,0.707287,25.577334,0.422666
13,jnissen,1.0,0,1.0,0,1.0,20,1.000000,0.000000,NaN,...,-3.134130,-0.156706,4.136039,0.206802,1.001910,0.050095,14.128238,0.706412,19.309649,0.690351
15,jtom,0.0,1,0.0,0,1.0,6,1.000000,0.000000,NaN,...,-0.461094,-0.076849,1.857967,0.309661,1.396873,0.232812,4.271495,0.711916,5.725838,0.274162
7,ebonnet,3.0,1,0.0,1,1.0,20,0.952381,0.000000,NaN,...,-1.914461,-0.091165,3.061402,0.145781,1.146941,0.054616,14.081239,0.670535,20.248997,-0.248997
6,tedmonds,0.0,3,1.0,0,1.0,24,1.000000,0.083333,1.000000,...,-3.557133,-0.148214,8.697742,0.362406,5.140609,0.214192,15.210239,0.633760,22.330916,1.669084
25,mling,0.0,0,0.0,0,1.0,2,1.000000,0.000000,NaN,...,-0.132562,-0.066281,0.127927,0.063963,-0.004635,-0.002317,1.165336,0.582668,1.965237,0.034763
0,jrandolph,3.0,3,3.0,0,0.0,36,1.000000,0.055556,1.000000,...,-5.864087,-0.162891,11.604178,0.322338,5.740091,0.159447,24.838076,0.689947,34.066275,1.933725
2,ochartock,4.0,1,2.0,1,0.0,24,0.960000,0.000000,NaN,...,-2.249380,-0.089975,4.748161,0.189926,2.498781,0.099951,17.560633,0.702425,23.957987,0.042013
8,tholland,2.0,1,0.0,0,0.0,14,1.000000,0.000000,NaN,...,-1.479889,-0.105706,3.313099,0.236650,1.833211,0.130944,9.692879,0.692348,13.447875,0.552125
11,gnorrbom,0.0,2,1.0,1,0.0,28,0.965517,0.000000,NaN,...,-2.619216,-0.090318,5.395726,0.186060,2.776510,0.095742,19.321057,0.666243,27.880162,0.119838
10,cweinberg,1.0,3,2.0,2,0.0,26,0.928571,0.071429,0.500000,...,-6.286353,-0.224513,9.501881,0.339353,3.215527,0.114840,18.682192,0.667221,25.960698,0.039302
9,cmccutche,3.0,0,3.0,0,0.0,8,1.000000,0.000000,NaN,...,-1.097751,-0.137219,1.757562,0.219695,0.659811,0.082476,5.565146,0.695643,7.716084,0.283916
12,tmonroe,2.0,1,2.0,2,0.0,25,0.925926,0.037037,0.000000,...,-5.628632,-0.208468,7.941811,0.294141,2.313179,0.085673,19.498720,0.722175,25.525410,-0.525410
14,jwodatch1,1.0,0,1.0,0,0.0,8,1.000000,0.000000,NaN,...,-1.035807,-0.129476,1.518304,0.189788,0.482497,0.060312,5.429142,0.678643,7.721033,0.278967
16,lhaberfie,0.0,1,0.0,0,0.0,4,1.000000,0.250000,1.000000,...,-1.768431,-0.442108,2.785561,0.696390,1.017130,0.254283,1.775719,0.443930,3.314070,0.685930
18,efortin,0.0,1,1.0,1,0.0,41,0.976190,0.000000,NaN,...,-3.105220,-0.073934,6.532857,0.155544,3.427636,0.081610,25.939136,0.617598,40.541974,0.458026
4,jwilliams,3.0,3,1.0,3,0.0,27,0.900000,0.100000,0.333333,...,-5.987222,-0.199574,9.187847,0.306262,3.200625,0.106688,19.317553,0.643918,27.469115,-0.469115
19,mmcdonnel,0.0,0,0.0,0,0.0,39,1.000000,0.000000,NaN,...,-5.908275,-0.151494,7.894130,0.202414,1.985854,0.050919,26.645604,0.683221,37.632263,1.367737
20,dbloodgoo,0.0,0,0.0,0,0.0,13,1.000000,0.000000,NaN,...,-1.428715,-0.109901,2.186175,0.168167,0.757460,0.058266,8.474978,0.651921,12.574671,0.425329
22,sjonas,0.0,0,0.0,0,0.0,5,1.000000,0.000000,NaN,...,-0.714745,-0.142949,0.806911,0.161382,0.092166,0.018433,3.236637,0.647327,4.850189,0.149811
21,jdean,0.0,0,1.0,0,0.0,7,1.000000,0.000000,NaN,...,-1.306248,-0.186607,1.255866,0.179409,-0.050382,-0.007197,4.784406,0.683487,6.798099,0.201901
23,ilee,0.0,0,0.0,0,0.0,3,1.000000,0.000000,NaN,...,-0.749223,-0.249741,0.546942,0.182314,-0.202281,-0.067427,2.084279,0.694760,2.909439,0.090561
24,amerriman,0.0,0,0.0,0,0.0,2,1.000000,0.000000,NaN,...,-0.320489,-0.160245,0.441987,0.220994,0.121498,0.060749,1.295990,0.647995,1.921159,0.078841
26,aagami,0.0,0,0.0,0,0.0,1,1.000000,0.000000,NaN,...,-0.367950,-0.367950,0.141211,0.141211,-0.226739,-0.226739,0.682778,0.682778,0.977640,0.022360
27,aolcese,0.0,0,0.0,0,0.0,1,1.000000,0.000000,NaN,...,0.060029,0.060029,0.179987,0.179987,0.240016,0.240016,0.590824,0.590824,0.946220,0.053780
28,cseamon,0.0,0,0.0,0,0.0,1,1.000000,0.000000,NaN,...,0.002012,0.002012,0.086222,0.086222,0.088234,0.088234,0.523527,0.523527,0.970955,0.029045
29,aroy,1.0,0,2.0,2,0.0,31,0.939394,0.060606,0.000000,...,-4.940995,-0.149727,5.363213,0.162522,0.422218,0.012794,19.702523,0.597046,31.152314,-0.152314
30,mbrownlee,0.0,0,0.0,1,0.0,8,0.888889,0.111111,0.000000,...,-2.151564,-0.239063,2.329463,0.258829,0.177899,0.019767,5.574731,0.619415,8.200691,-0.200691
31,rbergeron,0.0,0,0.0,1,0.0,3,0.750000,0.000000,NaN,...,-0.686652,-0.171663,-0.192795,-0.048199,-0.879447,-0.219862,2.627453,0.656863,3.846482,-0.846482
32,ktaylor,0.0,0,0.0,1,0.0,1,0.500000,0.000000,NaN,...,-0.016800,-0.008400,-0.598766,-0.299383,-0.615566,-0.307783,1.616365,0.808182,1.896954,-0.896954
33,salladi,0.0,0,0.0,1,0.0,1,0.500000,0.000000,NaN,...,-0.147948,-0.073974,-0.778599,-0.389299,-0.926547,-0.463273,0.966010,0.483005,1.935164,-0.935164
34,srueschem,0.0,0,4.0,2,0.0,35,0.945946,0.000000,NaN,...,-3.565237,-0.096358,5.295352,0.143118,1.730114,0.046760,23.710996,0.640838,35.704860,-0.704860
35,mlabar,0.0,0,0.0,2,0.0,3,0.600000,0.200000,0.000000,...,-1.591301,-0.318260,0.398217,0.079643,-1.193084,-0.238617,3.444451,0.688890,4.734047,-1.734047

In [8]:
result.thrower_stats.head(20)

,thrower,attempts,completions,turnovers,huck_attempts,huck_completions,avg_throw_distance,avg_field_y_delta,total_field_y_delta,total_xcp,...,total_total_aec,avg_total_aec,total_etv,avg_etv,expected_completions,completions_over_expected,completion_pct,huck_rate,huck_completion_pct,cpoe
0,aagami,1,1,0,0,0,16.112359,-13.840000,-13.84,0.977640,...,-0.226739,-0.226739,0.682778,0.682778,0.977640,0.022360,1.000000,0.000000,NaN,0.022360
1,adavis2,3,3,0,0,0,17.009500,11.976667,35.93,2.864090,...,0.444570,0.148190,1.900071,0.633357,2.864090,0.135910,1.000000,0.000000,NaN,0.045303
2,amerriman,2,2,0,0,0,17.320931,3.915000,7.83,1.921159,...,0.121498,0.060749,1.295990,0.647995,1.921159,0.078841,1.000000,0.000000,NaN,0.039420
3,aolcese,1,1,0,0,0,22.791974,22.300000,22.30,0.946220,...,0.240016,0.240016,0.590824,0.590824,0.946220,0.053780,1.000000,0.000000,NaN,0.053780
4,aroy,33,31,2,2,0,17.322645,8.071818,266.37,31.152314,...,0.422218,0.012794,19.702523,0.597046,31.152314,-0.152314,0.939394,0.060606,0.0,-0.004616
5,bjagt,19,19,0,1,1,15.158649,7.843684,149.03,17.961387,...,3.204629,0.168665,12.985366,0.683440,17.961387,1.038613,1.000000,0.052632,1.0,0.054664
6,cjurek,27,26,1,1,0,13.890912,6.659630,179.81,25.577334,...,3.290346,0.121865,19.096755,0.707287,25.577334,0.422666,0.962963,0.037037,0.0,0.015654
7,cmccutche,8,8,0,0,0,10.818045,6.161250,49.29,7.716084,...,0.659811,0.082476,5.565146,0.695643,7.716084,0.283916,1.000000,0.000000,NaN,0.035490
8,cseamon,1,1,0,0,0,19.029149,8.590000,8.59,0.970955,...,0.088234,0.088234,0.523527,0.523527,0.970955,0.029045,1.000000,0.000000,NaN,0.029045
9,cweinberg,28,26,2,2,1,18.321000,9.474643,265.29,25.960698,...,3.215527,0.114840,18.682192,0.667221,25.960698,0.039302,0.928571,0.071429,0.5,0.001404
10,dbloodgoo,13,13,0,0,0,13.346847,4.747692,61.72,12.574671,...,0.757460,0.058266,8.474978,0.651921,12.574671,0.425329,1.000000,0.000000,NaN,0.032718
11,ebonnet,21,20,1,0,0,13.351529,4.110952,86.33,20.248997,...,1.146941,0.054616,14.081239,0.670535,20.248997,-0.248997,0.952381,0.000000,NaN,-0.011857
12,efortin,42,41,1,0,0,14.300987,7.428095,311.98,40.541974,...,3.427636,0.081610,25.939136,0.617598,40.541974,0.458026,0.976190,0.000000,NaN,0.010905
13,gnorrbom,29,28,1,0,0,14.236657,5.760000,167.04,27.880162,...,2.776510,0.095742,19.321057,0.666243,27.880162,0.119838,0.965517,0.000000,NaN,0.004132
14,ilee,3,3,0,0,0,16.442270,-4.366667,-13.10,2.909439,...,-0.202281,-0.067427,2.084279,0.694760,2.909439,0.090561,1.000000,0.000000,NaN,0.030187
15,jdean,7,7,0,0,0,9.749188,-0.448571,-3.14,6.798099,...,-0.050382,-0.007197,4.784406,0.683487,6.798099,0.201901,1.000000,0.000000,NaN,0.028843
16,jmalks,29,27,2,2,2,16.688723,11.572069,335.59,27.428805,...,5.251217,0.181076,18.896001,0.651586,27.428805,-0.428805,0.931034,0.068966,1.0,-0.014786
17,jnissen,20,20,0,0,0,12.733278,3.849500,76.99,19.309649,...,1.001910,0.050095,14.128238,0.706412,19.309649,0.690351,1.000000,0.000000,NaN,0.034518
18,jrandolph,36,36,0,2,2,14.539390,8.263611,297.49,34.066275,...,5.740091,0.159447,24.838076,0.689947,34.066275,1.933725,1.000000,0.055556,1.0,0.053715
19,jtom,6,6,0,0,0,13.856287,7.770000,46.62,5.725838,...,1.396873,0.232812,4.271495,0.711916,5.725838,0.274162,1.000000,0.000000,NaN,0.045694

In [9]:
from ufa import (
    split_training_data,
    train_etv_models_from_split,
    evaluate_etv_model_bundle,
)

splits = split_training_data("../data/raw/all_games_1024.csv")

baseline_bundle = train_etv_models_from_split(splits)
baseline_results = evaluate_etv_model_bundle(baseline_bundle, splits)

baseline_results

,dataset,model,n,positive_rate,accuracy,auc,ppv,npv
0,train,cp,185093,0.938312,0.936583,0.788494,0.943015,0.431212
1,train,fv,186942,0.711317,0.711028,0.628491,0.712388,0.474766
2,validation,cp,46277,0.935584,0.934438,0.777733,0.940272,0.452080
3,validation,fv,46753,0.712104,0.711612,0.627445,0.712800,0.444444
4,temporal_test,cp,33762,0.942302,0.939755,0.793351,0.948062,0.418868
5,temporal_test,fv,34143,0.696248,0.694842,0.627865,0.697664,0.434426
6,player_test,cp,22804,0.942115,0.940186,0.777018,0.946397,0.417910
7,player_test,fv,22988,0.719027,0.718549,0.621423,0.720003,0.456693

In [12]:
from ufa import train_xgboost_etv_models_from_split

xgb_bundle = train_xgboost_etv_models_from_split(splits)

In [13]:
from ufa import compare_model_bundles, format_model_performance_table

comparison = compare_model_bundles(
    {"logistic": baseline_bundle, "xgboost": xgb_bundle},
    splits,
)

paper_table = format_model_performance_table(comparison)
paper_table

Column             FV Baseline  FV Model  CP Baseline  CP Model
Dataset  Metric
Random   Accuracy        0.712     0.730        0.934     0.937
         AUC             0.627     0.656        0.778     0.802
         PPV             0.713     0.734        0.940     0.940
         NPV             0.444     0.664        0.452     0.627
Temporal Accuracy        0.695     0.712        0.940     0.944
         AUC             0.628     0.653        0.793     0.813
         PPV             0.698     0.717        0.948     0.946
         NPV             0.434     0.642        0.419     0.597
Player   Accuracy        0.719     0.736        0.940     0.943
         AUC             0.621     0.654        0.777     0.803
         PPV             0.720     0.742        0.946     0.945
         NPV             0.457     0.647        0.418     0.548
Train    Accuracy        0.711     0.728        0.937     0.941
         AUC             0.628     0.668        0.788     0.825
         PPV             0.712     0.732        0.943     0.943
         NPV             0.475     0.652        0.431     0.710

In [14]:
latex = model_performance_table_to_latex(paper_table)
print(latex)

\begin{table}
\centering
\caption{CP and FV Model performance compared to baseline.}
\begin{tabular}{llrrrr}
\toprule
 & Metric & FV Baseline & FV Model & CP Baseline & CP Model \\
\midrule
\multirow{4}{*}{Random} & Accuracy & 0.712 & 0.730 & 0.934 & 0.937 \\
 & AUC & 0.627 & 0.656 & 0.778 & 0.802 \\
 & PPV & 0.713 & 0.734 & 0.940 & 0.940 \\
 & NPV & 0.444 & 0.664 & 0.452 & 0.627 \\
\midrule
\multirow{4}{*}{Temporal} & Accuracy & 0.695 & 0.712 & 0.940 & 0.944 \\
 & AUC & 0.628 & 0.653 & 0.793 & 0.813 \\
 & PPV & 0.698 & 0.717 & 0.948 & 0.946 \\
 & NPV & 0.434 & 0.642 & 0.419 & 0.597 \\
\midrule
\multirow{4}{*}{Player} & Accuracy & 0.719 & 0.736 & 0.940 & 0.943 \\
 & AUC & 0.621 & 0.654 & 0.777 & 0.803 \\
 & PPV & 0.720 & 0.742 & 0.946 & 0.945 \\
 & NPV & 0.457 & 0.647 & 0.418 & 0.548 \\
\midrule
\multirow{4}{*}{Train} & Accuracy & 0.711 & 0.728 & 0.937 & 0.941 \\
 & AUC & 0.628 & 0.668 & 0.788 & 0.825 \\
 & PPV & 0.712 & 0.732 & 0.943 & 0.943 \\
 & NPV & 0.475 & 0.652 & 0.431 & 0.710 \\
\bottomrule
\end{tabular}
\end{table}